version: "3"

services:
  nuxt-frontend:
    build:
      context: .
      dockerfile: .
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
    container_name: nuxt-frontend
    expose:
      - "${FRONTEND_CONTAINER_PORT}"
    volumes:
      - .:/nuxt-frontend
      - node_modules_volume:/nuxt-frontend/node_modules
    command: /bin/sh -c "rm -f tmp/pids/server.pid && yarn run dev"
    env_file: # アプリケーション内の環境変数もルート直下envファイルを参照
      - .${APP_ENV}.env
    networks:
      whale-network:
        ipv4_address: ${FRONTEND_CONTAINER_HOST}

  reverse-proxy:
    image: nginx:1.25.2-alpine
    volumes:
      - ./reverse-proxy:/etc/nginx
    ports:
      - ${REVERSE_PROXY_HTTPS_HOST_PORT}:${REVERSE_PROXY_HTTPS_CONTAINER_PORT}
    env_file:
      - .${APP_ENV}.env
    extra_hosts:
      - "${PROXY_HOST}:host-gateway"
    networks:
      - whale-network
    depends_on:
      - nuxt-frontend

volumes:
  node_modules_volume:

networks:
  whale-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${CONTAINER_NETWORK_SUBNET}
